### ISSUE TITLE
Unable to configure timeout

### ISSUE THREAD

**Issue by renanbr** [cosmicjs/cosmic-sdk-js#31]
Hello,

We're facing an issue about website unavailability when CosmicJs API doesn't work as expected.

We had an incident the 2023-09-15 when we're plugged to the API v2.

The API took too long (+30 seconds) to answer our request, which blocked our website to be rendered.

Since then we moved to the v3.

On 2023-10-20 we had the same behaviour, but this time the API get back to normal after some minutes.

The API v3 says the timeout is 10 seconds
https://www.cosmicjs.com/docs/api/request-limits#__next
but on 2023-10-20 the API was taking more than this to drop the request.

We would like to be able to set timeout to prevent having the same issue again.

Is this possible currently? We didn't found it in the SDK neither on the CosmicJS settings page.

Our setup:

- `nuxt` `2.17.1`
- `@cosmicjs/sdk`: `1.0.10`

**Comment by tonyspiro** [comment]
@renanbr Thank you for bringing this issue to our attention. We do not currently offer the ability to set timeouts on API requests. This issue may be due to your API payload size being too large, or perhaps you are attempting to return lots of nested data using Object relationship Metafields. If either is the case, we recommend using API payload limit strategies such as pagination using `limit` and `skip` and/or using `props` to limit the data being sent to only properties that you need (See [the docs](https://www.cosmicjs.com/docs/api/objects#get-objects) for more information on using `limit`,`skip` and `props`).

If you are using these strategies and are still seeing timeout issues, please reach out to support@cosmicjs.com with the details of your API request and we will take a look. I'm closing this issue for now.
